/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import org.springframework.validation.annotation.Validated;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-11-08T15:34:45.022Z[GMT]")
@Validated
public interface HitApi {

//    @Operation(summary = "Сохранение информации о том, что к эндпоинту был запрос", description = "Сохранение информации о том, что на uri конкретного сервиса был отправлен запрос пользователем. Название сервиса, uri и ip пользователя указаны в теле запроса.", tags={ "StatsController" })
//    @ApiResponses(value = {
//        @ApiResponse(responseCode = "200", description = "Информация сохранена") })
//    @RequestMapping(value = "/hit",
//        consumes = { "application/json" },
//        method = RequestMethod.POST)
//    ResponseEntity<Void> hit(@Parameter(in = ParameterIn.DEFAULT, description = "данные запроса", required=true, schema=@Schema()) @Valid @RequestBody EndpointHit body);

}

